# Generated by Django 3.0.2 on 2020-01-25 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリ名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='削除日時')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='サブカテゴリ名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='削除日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hp.Category', verbose_name='カテゴリID')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='削除日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hp.Category', verbose_name='カテゴリID')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hp.SubCategory', verbose_name='サブカテゴリID')),
            ],
        ),
    ]
