version: '3'
services:
  attakait_app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: python:3.7
    volumes:
      - '.:/var/www/html'
    container_name: attakait_hp
    tty: true
    working_dir: '/var/www/html'
    ports:
      - 8000:8000
    command:
      gunicorn attakait_hp.wsgi --log-file -